### ISSUE TITLE
Fix RWD in website for senior high school

### ISSUE THREAD

**Issue by jayin92** [NCTUCSUnion/highschool_website#1]
![Image](https://github.com/NCTUCSUnion/highschool_website/assets/11909159/2e219e42-7f86-4966-97fb-262e592ac05c)

Navbar 沒有背景色，非常不明顯。

**Comment by ChuEating1005** [comment]
已完成, 發PR等review中

![Image](https://github.com/NCTUCSUnion/highschool_website/assets/129883603/d565fdf1-99c8-4774-802e-eb621771d53c)

**Comment by jayin92** [comment]
Done
